title: <p align="center"> Divya Sodha </p>
logo: assets/img/logo4.jpg
description: 
 <p align="center">
  <a href="https://www.linkedin.com/in/divyasodha7537/">LinkedIn</a> |
  <a href="https://github.com/Divya10Sodha">GitHub</a>
 <br/> I am an IT Professional aiming to gain and apply knowledge in the field of Big Data and AI and be a part of the team that helps me to expertise my skills.  
 </p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
