title: <p align="center"> Divya Sodha </p>
logo: <center><img src="/assets/img/divya.jpg "/></center>
description: I am an IT Professional aiming to gain and apply knowledge in the field of Big Data and AI and be a part of the team that helps me to expertise my skills.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
